# Load the .profile if present
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

# Set DOTFILES_ROOT
export DOTFILES_ROOT=${DOTFILES_ROOT:-"$HOME/.darwin_dotfiles"}

# Core PATH setup
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Core sources
source $DOTFILES_ROOT/lib/core/dotfiles.sh
source $DOTFILES_ROOT/lib/core/exports.sh
source $DOTFILES_ROOT/lib/core/git.sh
source $DOTFILES_ROOT/lib/core/update.sh

# MacOS
if [ "$(uname)" = "Darwin" ]; then
	export BASH_SILENCE_DEPRECATION_WARNING=1
	
	# Darwin sources
	source $DOTFILES_ROOT/lib/darwin/ps1.sh
	source $DOTFILES_ROOT/lib/darwin/brew.sh
	source $DOTFILES_ROOT/lib/darwin/common.sh
	source $DOTFILES_ROOT/lib/darwin/rbenv.sh
	source $DOTFILES_ROOT/lib/darwin/openjdk.sh
	source $DOTFILES_ROOT/lib/darwin/flutter.sh
	source $DOTFILES_ROOT/lib/darwin/node.sh
	source $DOTFILES_ROOT/lib/darwin/python3.sh
	source $DOTFILES_ROOT/lib/darwin/android.sh
fi 
