# Dotfile Variables
export DOTFILES_PS1=1 											 # Change to 0 to enable custom PS1
export DOTFILE_EXPORTS=1                     # Change to 0 to enable custom exports
export GOOGLE_PLACES_API_KEY="YOUR_KEY_HERE" # Change to valid API key

# Load the .zprofile if present
[[ -s "$HOME/.zprofile" ]] && source "$HOME/.zprofile"

# Set DOTFILES_ROOT
export DOTFILES_ROOT=${DOTFILES_ROOT:-"$HOME/.darwin_dotfiles"}

# Core PATH setup
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Core sources
source $DOTFILES_ROOT/lib/core/dotfiles.sh
source $DOTFILES_ROOT/lib/core/exports.sh
source $DOTFILES_ROOT/lib/core/git.sh
source $DOTFILES_ROOT/lib/core/update.sh

# MacOS
if [ "$(uname)" = "Darwin" ]; then
	# Darwin sources
	source $DOTFILES_ROOT/lib/darwin/ps1.sh
	source $DOTFILES_ROOT/lib/darwin/brew.sh
	source $DOTFILES_ROOT/lib/darwin/common.sh
	source $DOTFILES_ROOT/lib/darwin/flutter.sh
	source $DOTFILES_ROOT/lib/darwin/android.sh
fi 